version: '2.4'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [jupyter, lab]
    environment:
      JUPYTER_PORT: ${JUPYTER_PORT}
    command: ["--ip=0.0.0.0", "--port=${JUPYTER_PORT}", "--no-browser", "--allow-root"]
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
